product:
    resource: "@ProductBundle/Controller/"
    prefix:   /
    type: annotation

hunt_kingdom:
    resource: "@HuntKingdomBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

gestion_event:
    resource: "@GestionEventBundle/Resources/config/routing.yml"
    prefix:   /

imen:
    resource: "@ImenBundle/Resources/config/routing.yml"
    prefix:   /
users:
    resource: "@UsersBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

groups_groups:
    resource: "@GroupsBundle/Controller/GroupsController.php"
    prefix:   /
    type:     annotation

groups:
    resource: "@GroupsBundle/Resources/config/routing.yml"
    prefix:   /

client:
    resource: "@UsersBundle/Resources/config/routing/client.yml"
    prefix: /

    
