user_index:
    path:     /
    defaults: { _controller: "UsersBundle:User:index" }
    methods:  GET

user_show:
    path:     /{id}/show
    defaults: { _controller: "UsersBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "UsersBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "UsersBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "UsersBundle:User:delete" }
    methods:  DELETE

